version: '3.1'
services:
  spotify-kafka:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    hostname: localhost
    container_name: spotify-kafka
    environment:
      - "ADVERTISED_HOST=localhost"
      - "ADVERTISED_PORT=9092"
      - "AUTO_CREATE_TOPICS=true"
    command: >
      bash -c
      "(sleep 15s &&
      /opt/kafka_2.11-0.10.1.0/bin/kafka-topics.sh
      --create
      --zookeeper
      localhost:2181 --replication-factor 1 --partitions 1 &) && (supervisord -n)"
